#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ky Lee <kyhyeunlee@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# load aliases
if [[ -s "$HOME/.zsh-config/alias.zsh" ]]; then
  source "$HOME/.zsh-config/alias.zsh"
fi

# load fzf stuff
if [[ -s "$HOME/.zsh-config/fzf.zsh" ]]; then
  source "$HOME/.zsh-config/fzf.zsh"
fi

# Path
export NVM_DIR="$HOME/.nvm"
export PATH="$PATH:$HOME/code/bin/arcanist/bin"

#export GOPATH="$HOME/code/go"
#export PATH="$PATH:/usr/local/go/bin"

source ~/code/bin/tmuxinator.zsh

unsetopt correct
